# baseURL: 'http://localhost:1313'
baseURL: 'https://Tiziano-Caruana.github.io'
title: 'Tiziano Caruana'
theme: 'PaperMod'
paginate: 5
images: /static/favicon.ico
enableRobotsTXT: true

languages:
  en:
    languageName: English
    weight: 1
    taxonomies:
      tag: tags
      category: categories
      series: series
    menu:
      main:
        - name: About me
          url: about_me
          weight: 1
        - name: Blog
          url: tags/blog
          weight: 2
        - name: Writeup
          url: tags/writeup
          weight: 2
    params:
        homeInfoParams:
          Title: Hi, I'm Titto!
          Content: I'm an 19 year old student at La Sapienza University of Rome, where I'm studying computer engineering and playing CTFs for [TRX](https://theromanxpl0it.github.io/). No need to OSINT to know more [about me](https://tiziano-caruana.github.io/about_me/)

  it:
    languageName: Italiano
    weight: 2
    taxonomies:
      tag: tags
      category: categories
      series: series
    menu:
      main:
        - name: Chi sono
          url: about_me
          weight: 1
        - name: Blog
          url: tags/blog
          weight: 2
        - name: Writeup
          url: tags/writeup
          weight: 2
    params:
      homeInfoParams:
        Title: Ciao, sono Titto!
        Content: Sono uno studente di 19 anni presso l'Università La Sapienza di Roma, dove studio ingegneria informatica e gioco CTF con i [TRX](https://theromanxpl0it.github.io/). Non c'è bisogno di OSINTare per saperne di più [su di me](https://tiziano-caruana.github.io/it/about_me/)

params:
    env: production
    description: "Tiziano Caruana's personal website"
    defaultTheme: auto

    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true

    socialIcons: # optional
        - name: 'Twitter'
          url: 'https://twitter.com/TittoCaru'
        - name: 'LinkedIn'
          url: 'https://www.linkedin.com/in/tiziano-caruana/'
        - name: 'GitHub'
          url: 'https://github.com/Tiziano-Caruana'


    assets:
      favicon: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNvCmIE7HEiLhByQCf2_uMI9ENQNto_kSmOjKv-BusCjO355SvJeQZmWMPBXS6wwaH7nQ&usqp=CAU'

    analytics:
      google:
        SiteVerificationTag: '-NRlyU37XYTZJ4WyeO8svRuXL8xXbOUAqLrx-qYbEpw'

sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 1
